<#
.SYNOPSIS
    Configure les hooks Git pour le projet MedSecure

.DESCRIPTION
    Ce script installe les hooks Git locaux pour :
    - Valider le format des commits (Conventional Commits)
    - Vérifier l'absence de secrets (Gitleaks)
    - Formater le code automatiquement (dotnet format)
    - Exécuter les tests unitaires avant commit

.PARAMETER SkipTests
    Ne pas exécuter les tests dans le pre-commit hook

.PARAMETER Force
    Écraser les hooks existants

.EXAMPLE
    .\Setup-GitHooks.ps1

.EXAMPLE
    .\Setup-GitHooks.ps1 -SkipTests -Force
#>

[CmdletBinding()]
param(
    [switch]$SkipTests,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# ============================================
# Configuration
# ============================================
$projectRoot = $PSScriptRoot
$hooksDir = Join-Path $projectRoot ".git\hooks"

# ============================================
# Functions
# ============================================

function Write-Header {
    param([string]$Message)
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host " $Message" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
}

function Write-Step {
    param([string]$Message)
    Write-Host "→ $Message" -ForegroundColor Yellow
}

function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Write-Error {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Test-GitRepository {
    if (-not (Test-Path (Join-Path $projectRoot ".git"))) {
        Write-Error "Pas un repository Git !"
        throw "Not a git repository"
    }
}

function Install-PreCommitHook {
    Write-Header "Installation du pre-commit hook"

    $hookPath = Join-Path $hooksDir "pre-commit"

    if ((Test-Path $hookPath) -and -not $Force) {
        Write-Warning "Le hook pre-commit existe déjà. Utilisez -Force pour écraser."
        return
    }

    $hookContent = @'
#!/bin/sh
# MedSecure Pre-Commit Hook
# Auto-generated by Setup-GitHooks.ps1

echo "🔍 Running pre-commit checks..."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================
# 1. Check for secrets (Gitleaks)
# ============================================
echo "${YELLOW}→ Checking for secrets...${NC}"

if command -v gitleaks >/dev/null 2>&1; then
    gitleaks protect --staged --verbose
    if [ $? -ne 0 ]; then
        echo "${RED}✗ Secrets detected! Remove them before committing.${NC}"
        echo "${YELLOW}Hint: Add false positives to .gitleaksignore${NC}"
        exit 1
    fi
    echo "${GREEN}✓ No secrets detected${NC}"
else
    echo "${YELLOW}⚠ Gitleaks not installed, skipping secret detection${NC}"
    echo "  Install: https://github.com/gitleaks/gitleaks#installation"
fi

# ============================================
# 2. Format code (dotnet format)
# ============================================
echo "${YELLOW}→ Checking code formatting...${NC}"

dotnet format --verify-no-changes --verbosity quiet
if [ $? -ne 0 ]; then
    echo "${RED}✗ Code formatting issues detected${NC}"
    echo "${YELLOW}Run 'dotnet format' to fix formatting${NC}"
    exit 1
fi
echo "${GREEN}✓ Code formatting OK${NC}"

# ============================================
# 3. Build check
# ============================================
echo "${YELLOW}→ Building solution...${NC}"

dotnet build --configuration Debug --verbosity quiet --no-restore
if [ $? -ne 0 ]; then
    echo "${RED}✗ Build failed!${NC}"
    exit 1
fi
echo "${GREEN}✓ Build successful${NC}"

# ============================================
# 4. Run unit tests (optional)
# ============================================
'@ + $(if (-not $SkipTests) {
@'

echo "${YELLOW}→ Running unit tests...${NC}"

dotnet test --filter "Category=Unit" --no-build --verbosity quiet
if [ $? -ne 0 ]; then
    echo "${RED}✗ Unit tests failed!${NC}"
    exit 1
fi
echo "${GREEN}✓ Unit tests passed${NC}"
'@
} else {
@'

echo "${YELLOW}⚠ Unit tests skipped (configured in Setup-GitHooks.ps1)${NC}"
'@
}) + @'


echo "${GREEN}✅ All pre-commit checks passed!${NC}"
exit 0
'@

    # Écrire le hook
    $hookContent | Out-File -FilePath $hookPath -Encoding utf8 -NoNewline

    # Rendre le hook exécutable (Windows n'a pas chmod, mais Git le détectera)
    git update-index --chmod=+x $hookPath 2>&1 | Out-Null

    Write-Success "Pre-commit hook installé"
}

function Install-CommitMsgHook {
    Write-Header "Installation du commit-msg hook"

    $hookPath = Join-Path $hooksDir "commit-msg"

    if ((Test-Path $hookPath) -and -not $Force) {
        Write-Warning "Le hook commit-msg existe déjà. Utilisez -Force pour écraser."
        return
    }

    $hookContent = @'
#!/bin/sh
# MedSecure Commit-Msg Hook
# Validates Conventional Commits format

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Regex for Conventional Commits
# Format: <type>(<scope>): <description>
regex='^(feat|fix|docs|style|refactor|perf|test|chore|ci|security|build|revert)(\([a-z0-9-]+\))?: .{1,100}'

if ! echo "$commit_msg" | grep -qE "$regex"; then
    echo "${RED}✗ Invalid commit message format!${NC}"
    echo ""
    echo "${YELLOW}Expected format:${NC} <type>(<scope>): <description>"
    echo ""
    echo "${YELLOW}Valid types:${NC}"
    echo "  feat     - New feature"
    echo "  fix      - Bug fix"
    echo "  docs     - Documentation only"
    echo "  style    - Code style/formatting"
    echo "  refactor - Refactoring"
    echo "  perf     - Performance improvement"
    echo "  test     - Adding tests"
    echo "  chore    - Maintenance"
    echo "  ci       - CI/CD changes"
    echo "  security - Security patch"
    echo ""
    echo "${YELLOW}Examples:${NC}"
    echo "  feat(patients): add search by SSN"
    echo "  fix(auth): resolve token expiration"
    echo "  security(sql): prevent SQL injection"
    echo "  docs(readme): update setup instructions"
    echo ""
    echo "${YELLOW}Your commit message:${NC}"
    echo "  $commit_msg"
    exit 1
fi

echo "${GREEN}✓ Commit message format valid${NC}"
exit 0
'@

    # Écrire le hook
    $hookContent | Out-File -FilePath $hookPath -Encoding utf8 -NoNewline

    # Rendre le hook exécutable
    git update-index --chmod=+x $hookPath 2>&1 | Out-Null

    Write-Success "Commit-msg hook installé"
}

function Install-PrePushHook {
    Write-Header "Installation du pre-push hook"

    $hookPath = Join-Path $hooksDir "pre-push"

    if ((Test-Path $hookPath) -and -not $Force) {
        Write-Warning "Le hook pre-push existe déjà. Utilisez -Force pour écraser."
        return
    }

    $hookContent = @'
#!/bin/sh
# MedSecure Pre-Push Hook
# Runs additional checks before pushing

echo "🚀 Running pre-push checks..."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# 1. Run all tests
# ============================================
echo "${YELLOW}→ Running all tests...${NC}"

dotnet test --verbosity quiet
if [ $? -ne 0 ]; then
    echo "${RED}✗ Tests failed! Fix them before pushing.${NC}"
    exit 1
fi
echo "${GREEN}✓ All tests passed${NC}"

# ============================================
# 2. Check for TODO/FIXME in committed files
# ============================================
echo "${YELLOW}→ Checking for unresolved TODOs...${NC}"

todo_count=$(git diff main...HEAD | grep -E "^\+.*TODO|^\+.*FIXME" | wc -l)
if [ "$todo_count" -gt 0 ]; then
    echo "${YELLOW}⚠ Warning: Found $todo_count TODO/FIXME in your changes${NC}"
    echo "  Consider resolving them before pushing to main/develop"
    # Not blocking, just a warning
fi

echo "${GREEN}✅ Pre-push checks passed!${NC}"
exit 0
'@

    # Écrire le hook
    $hookContent | Out-File -FilePath $hookPath -Encoding utf8 -NoNewline

    # Rendre le hook exécutable
    git update-index --chmod=+x $hookPath 2>&1 | Out-Null

    Write-Success "Pre-push hook installé"
}

function Test-Prerequisites {
    Write-Header "Vérification des prérequis"

    # Git
    try {
        $gitVersion = git --version
        Write-Success "Git installé : $gitVersion"
    }
    catch {
        Write-Error "Git n'est pas installé"
        throw
    }

    # .NET
    try {
        $dotnetVersion = dotnet --version
        Write-Success ".NET SDK installé : $dotnetVersion"
    }
    catch {
        Write-Error ".NET SDK n'est pas installé"
        throw
    }

    # Gitleaks (optionnel)
    try {
        $gitleaksVersion = gitleaks version 2>&1
        Write-Success "Gitleaks installé : $gitleaksVersion"
    }
    catch {
        Write-Warning "Gitleaks n'est pas installé (recommandé)"
        Write-Host "  Installation : https://github.com/gitleaks/gitleaks#installation" -ForegroundColor Yellow
    }
}

function Show-Summary {
    Write-Host ""
    Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║   ✅ Git Hooks installés avec succès !                     ║" -ForegroundColor Green
    Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "Hooks installés :" -ForegroundColor Cyan
    Write-Host "  • pre-commit  - Vérifie secrets, format, build, tests" -ForegroundColor White
    Write-Host "  • commit-msg  - Valide format Conventional Commits" -ForegroundColor White
    Write-Host "  • pre-push    - Exécute tous les tests" -ForegroundColor White
    Write-Host ""
    Write-Host "Les hooks s'exécuteront automatiquement :" -ForegroundColor Cyan
    Write-Host "  → À chaque commit (pre-commit, commit-msg)" -ForegroundColor White
    Write-Host "  → À chaque push (pre-push)" -ForegroundColor White
    Write-Host ""
    Write-Host "Pour désactiver temporairement :" -ForegroundColor Yellow
    Write-Host "  git commit --no-verify" -ForegroundColor White
    Write-Host ""
    Write-Host "Bon développement ! 🚀" -ForegroundColor Green
}

# ============================================
# Main Execution
# ============================================

try {
    Write-Host ""
    Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║   MedSecure - Configuration Git Hooks                     ║" -ForegroundColor Cyan
    Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan

    # Verify Git repository
    Test-GitRepository

    # Check prerequisites
    Test-Prerequisites

    # Create hooks directory if not exists
    if (-not (Test-Path $hooksDir)) {
        New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
    }

    # Install hooks
    Install-PreCommitHook
    Install-CommitMsgHook
    Install-PrePushHook

    # Summary
    Show-Summary
}
catch {
    Write-Error "Erreur lors de l'installation des hooks : $_"
    exit 1
}
